// <auto-generated />
namespace HelpDesk.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ConfigureonetoonerelationshipbetweenUserandSettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfigureonetoonerelationshipbetweenUserandSettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201611131522023_Configure one-to-one relationship between User and Settings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
